### ISSUE TITLE
I am not able to use angular ng-repeat directive in it

### ISSUE THREAD

**Issue by WorldOfTerror** [AndreaLombardo/BootSideMenu#14]
I am using anuglar ng-repeat to show list of item in UL format but i am not able to do it. So please look to this matter.

**Comment by AndreaLombardo** [comment]
Hi @WorldOfTerror
Unfortunately I'm not skilled in Angular and I can't help you.
Perhaps you need to instantiate the plugin methods after angular build your menu.

**Comment by Cadenei** [comment]
It happens because the plugin on these lines:

`newCode = "<div class=\"row\">";`
`newCode += "	<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12\">\n" + initialCode + " </div>";`
`newCode += "</div>";`
`newCode += "<div class=\"toggler\" data-whois=\"toggler\">";`
`newCode += "	<span class=\"glyphicon\">&nbsp;</span>";`
`newCode += "</div>";`

`this.empty();`
`this.append(newCode);`

Removes the original markup, that angular has attached events to, adds to it, and then puts it back.

I solved this problem by manually adding the markup that these lines are creating to my page and commenting out this part of the plugin.
