### ISSUE TITLE
Open/Close menu programmatically 

### ISSUE THREAD

**Issue by Rapid0s** [AndreaLombardo/BootSideMenu#24]
Is there any way to expose open/close/toggle functionality through a method/function ?

**Comment by AndreaLombardo** [comment]
Hi @Rapid0s 
hope is just you need ;-)

**Comment by igorski88** [comment]
I believe this is still an issue. calling .open or .close doesn't work. Come to find out it doesn't work in the example either: https://andrealombardo.github.io/BootSideMenu/examples/11-remote-control.html
Hope you can give me an idea of how to fix this since I love this BootsideMenu. It fits my needs perfectly.
